name: ydbs

on:
  schedule:
    - cron: "* 6 * * *"  # JST 15:00
  push:
    branches:
      - main
  workflow_dispatch: []

env:
  PRODUCT_ID: ${{secrets.PRODUCT_ID}}
  SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
  SLACK_CHANNEL: ${{secrets.SLACK_CHANNEL}}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Execute script
        run: python main.py
